# Generated by Django 4.2.13 on 2024-05-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botreply', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=200)),
            ],
        ),
    ]
